name: lemon_pizza
description: order a pizza online
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_bloc:
    path: C:\Users\Jerome\github\dart\bloc-master\packages\flutter_bloc

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
