name: lemon_pizza_ui
description: the ui layer for lemon pizza

version: 1.0.88

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  golden_ratio: ^1.0.6
  cupertino_icons: ^1.0.2
  animations: ^2.0.7
  system_theme: ^2.1.0
  flutter_colorpicker: ^1.0.3
  flutter_bloc: ^8.1.3
  formz: ^0.6.0

  flutter:
    sdk: flutter

  lemon_pizza_domain:
     path: packages/lemon_pizza_domain

  lemon_widgets:
    path: C:\Users\Jerome\github\dart\lemon_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CabinSketch
      fonts:
        - asset: assets/fonts/CabinSketch-Bold.ttf
        - asset: assets/fonts/CabinSketch-Regular.ttf
    - family: Niconne
      fonts:
        - asset: assets/fonts/Niconne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf